CFLAGS = -std=c99 -g
  
all: Project2_S1

Project2_S1: main.o Opcodes.o
	$(CC) $(CFLAGS) -o Project2_S1 Opcodes.o main.o

main.o: main.c Vars.h
	$(CC) $(CFLAGS) -c main.c -o main.o

Opcodes.o: Opcodes.c Vars.h
	$(CC) $(CFLAGS) -c Opcodes.c -o Opcodes.o
